<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence\User;

use App\Domain\User\User;
use App\Domain\User\UserNotFoundException;
use App\Domain\User\UserRepository;
use PDO;

class PDOUserRepository implements UserRepository
{
    private PDO $connection;

    public function __construct(PDO $connection)
    {
        $this->connection = $connection;
    }

    /**
     * {@inheritdoc}
     */
    public function findAll(): array
    {
        $stmt = $this->connection->query('SELECT * FROM users');
        return array_map(function ($row) {
            return $this->createUserFromRow($row);
        }, $stmt->fetchAll());
    }

    /**
     * {@inheritdoc}
     */
    public function findUserOfId(string $id): User
    {
        $stmt = $this->connection->prepare('SELECT * FROM users WHERE id = :id');
        $stmt->execute(['id' => $id]);
        $row = $stmt->fetch();

        if (!$row) {
            throw new UserNotFoundException();
        }

        return $this->createUserFromRow($row);
    }

    /**
     * {@inheritdoc}
     */
    public function findByEmail(string $email): User
    {
        $stmt = $this->connection->prepare('SELECT * FROM users WHERE email = :email');
        $stmt->execute(['email' => $email]);
        $row = $stmt->fetch();

        if (!$row) {
            throw new UserNotFoundException();
        }

        return $this->createUserFromRow($row);
    }

    public function create(User $user): User
    {
        // Generate UUID if not present (in a real scenario, use ramsey/uuid)
        // For now, we assume standard UUID v4 format from a helper or simple/native generation
        // But since we are strict, let's just generate a simple one or assume strictness.
        // Let's assume the helper is not available and do a raw one for now to keep it dependency-free-ish
        // or just let the database handle it if it was auto-inc, but it's char(36).
        
        $id = $user->getId();
        if (empty($id)) {
            $id = $this->generateUuid();
             // Recreate user with ID (since it's immutable-ish in constructor)
             // Actually, User has no setters for ID. We might need to handle this.
             // For this example, let's assume we pass a new User object.
             // But wait, our User domain object is constructed with ID.
             // Let's Reflect or change logic.
             // Best practice: The ID should probably be generated by the Domain Service before calling create,
             // OR create returns a new User instance with the ID.
             // Let's create a new instance here to return with the ID.
        }

        $stmt = $this->connection->prepare('
            INSERT INTO users (id, firstname, lastname, email, password)
            VALUES (:id, :firstname, :lastname, :email, :password)
        ');

        $stmt->execute([
            'id' => $id,
            'firstname' => $user->getFirstName(),
            'lastname' => $user->getLastName(),
            'email' => $user->getEmail(),
            'password' => $user->getPassword(), // Already hashed by the Action/Service
        ]);

        return new User($id, $user->getFirstName(), $user->getLastName(), $user->getEmail(), $user->getPassword());
    }

    public function update(User $user): User
    {
        // Check if exists
        $this->findUserOfId($user->getId());

        $sql = 'UPDATE users SET firstname = :firstname, lastname = :lastname, email = :email';
        $params = [
            'id' => $user->getId(),
            'firstname' => $user->getFirstName(),
            'lastname' => $user->getLastName(),
            'email' => $user->getEmail(),
        ];

        if ($user->getPassword()) {
            $sql .= ', password = :password';
            $params['password'] = $user->getPassword();
        }

        $sql .= ' WHERE id = :id';

        $stmt = $this->connection->prepare($sql);
        $stmt->execute($params);

        return $user;
    }

    public function delete(string $id): bool
    {
        // Check if exists
        $this->findUserOfId($id);

        $stmt = $this->connection->prepare('DELETE FROM users WHERE id = :id');
        return $stmt->execute(['id' => $id]);
    }

    private function createUserFromRow(array $row): User
    {
        return new User(
            $row['id'],
            $row['firstname'],
            $row['lastname'],
            $row['email'],
            $row['password'] ?? null // Might not select password always
        );
    }

    private function generateUuid(): string
    {
        return sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff), mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000,
            mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
        );
    }
}
